<?php

declare(strict_types=1);

namespace Burki24\SymconModuleHelper;

use InvalidArgumentException;
use UnexpectedValueException;

/**
 * Provides common infrastructure for SVG previews in Symcon configuration forms.
 *
 * Consumers remain responsible for generating trusted, self-contained SVG
 * markup and for the domain-specific preview design.
 *
 * @version 1.0.0
 */
final class SVGPreviewHelper
{
    private const DATA_URI_PREFIX = 'data:image/svg+xml;base64,';

    /**
     * Encodes trusted, self-contained SVG markup as a configuration-form data URI.
     *
     * This method verifies the SVG document root but does not sanitize arbitrary
     * SVG markup. Dynamic text and attribute values must be escaped before the
     * markup is passed to this method.
     *
     * @param string $svg Trusted SVG markup generated by the consumer.
     *
     * @return string Base64-encoded SVG data URI.
     *
     * @throws InvalidArgumentException If the value is not an SVG document.
     */
    public static function dataUri(string $svg): string
    {
        $normalized = str_starts_with($svg, "\xEF\xBB\xBF") ? substr($svg, 3) : $svg;
        if (preg_match('/^\s*(?:<\?xml\s[^?]*\?>\s*)?<svg(?:\s|>)/i', $normalized) !== 1) {
            throw new InvalidArgumentException('The preview content must be an SVG document.');
        }

        return self::DATA_URI_PREFIX . base64_encode($svg);
    }

    /**
     * Escapes a dynamic text or attribute value for inclusion in SVG markup.
     *
     * @param string $value Untrusted or dynamic preview value.
     *
     * @return string XML-safe SVG value.
     */
    public static function escape(string $value): string
    {
        return htmlspecialchars($value, ENT_QUOTES | ENT_XML1, 'UTF-8');
    }

    /**
     * Returns a configuration form with one named Image field initialized from SVG markup.
     *
     * The original form array is not modified. The field name must identify exactly
     * one element with type Image, including elements nested in panels or popups.
     *
     * @param array<string,mixed> $form Configuration form to update.
     * @param string $fieldName Stable name of the target Image element.
     * @param string $svg Trusted SVG markup generated by the consumer.
     *
     * @return array<string,mixed> Updated configuration form.
     *
     * @throws InvalidArgumentException If the field name is empty or the value is not an SVG document.
     * @throws UnexpectedValueException If the target Image field is missing or occurs more than once.
     */
    public static function withImage(array $form, string $fieldName, string $svg): array
    {
        $fieldName = trim($fieldName);
        if ($fieldName === '') {
            throw new InvalidArgumentException('The SVG preview field name must not be empty.');
        }

        $dataUri = self::dataUri($svg);
        $matches = 0;
        self::injectImage($form, $fieldName, $dataUri, $matches);

        if ($matches !== 1) {
            throw new UnexpectedValueException(sprintf(
                'The SVG preview field "%s" must identify exactly one Image element; found %d.',
                $fieldName,
                $matches
            ));
        }

        return $form;
    }

    /**
     * Recursively injects a data URI into matching Image elements.
     *
     * @param array<mixed> $node Current configuration-form node.
     * @param string $fieldName Stable name of the target Image element.
     * @param string $dataUri Base64-encoded SVG data URI.
     * @param int $matches Number of matching Image elements.
     */
    private static function injectImage(array &$node, string $fieldName, string $dataUri, int &$matches): void
    {
        if (($node['type'] ?? null) === 'Image' && ($node['name'] ?? null) === $fieldName) {
            $node['image'] = $dataUri;
            ++$matches;
        }

        foreach ($node as &$value) {
            if (is_array($value)) {
                self::injectImage($value, $fieldName, $dataUri, $matches);
            }
        }
        unset($value);
    }
}
