name: Check Style

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Check Symcon PHP style
        uses: symcon/action-style@v3
